name: 'Hello World'
description: 'Greet someone and record the time'
author: 'Pranab Paul'
inputs:
  who-to-greet:
    description: 'Who to greet'
    default: 'World'
    required: true
outputs:
  time: 
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'